#!/usr/bin/env python3
"""Fail CI on *new* mypy errors while tolerating a frozen baseline of old ones.

Why this exists
---------------
The mypy job used to run with ``continue-on-error: true``, so it reported green
even when it failed. That mattered here more than in most repos: the test suite
substitutes ``ctx`` with a bare ``AsyncMock`` everywhere, so a regression in how
the server talks to the MCP client passes every test. When ``await`` was
stripped from 116 ``ctx.info(...)`` call sites during the mcp 2.x migration, the
suite stayed green and mypy was the only signal that caught it.

Making the job blocking outright would have turned CI red on pre-existing debt,
so instead the current errors are frozen in ``tools/mypy_baseline.txt`` and only
regressions beyond that baseline fail.

Normalization
-------------
A baseline keyed on line numbers churns on every unrelated edit above an error.
So entries are keyed on ``(file, error-code)`` with a count, and line numbers are
discarded. Moving code around does not touch the baseline; introducing a new
*kind* of error, or more of an existing kind in the same file, does.

Comparison is deliberately asymmetric
-------------------------------------
CI runs ubuntu / py3.11 / ``pip install -e .[dev]``. A local dev venv typically
has optional extras installed too, so the two environments resolve a different
set of modules and can legitimately produce slightly different error sets. A
strict two-way ratchet would then fail on environment drift rather than on real
regressions.

    new key, or higher count  -> FAIL
    disappeared, lower count  -> warn, non-fatal, and suggest --update

That blocks regressions reliably without CI flapping. Tighten to a hard ratchet
if the drift turns out not to happen in practice.

Usage
-----
    python tools/check_mypy_baseline.py            # check, used by CI
    python tools/check_mypy_baseline.py --update   # rewrite the baseline
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = REPO_ROOT / "tools" / "mypy_baseline.txt"
TARGET = "src"

# "src/foo/bar.py:123: error: Some message  [error-code]"
# Note there are no CLI flags here on purpose: everything mypy needs lives in
# [tool.mypy] in pyproject.toml, so this run and a bare `mypy src` agree.
ERROR_RE = re.compile(r"^(?P<file>[^:]+):\d+: error: .*?\[(?P<code>[a-z-]+)\]$")

HEADER = """\
# Frozen mypy errors. Generated by tools/check_mypy_baseline.py --update.
#
# Format: <count>\t<posix-path>\t<error-code>
#
# This file is debt, not a target. Entries should only ever be removed. If a
# line disappears because you fixed something, re-run with --update.
"""


def run_mypy() -> str:
    """Run mypy over the target and return its combined output."""
    proc = subprocess.run(
        [sys.executable, "-m", "mypy", TARGET],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    output = proc.stdout + proc.stderr
    # mypy exits 1 when it finds errors, which is the normal case here. A
    # higher code means mypy itself failed (bad config, crash, missing plugin)
    # and the run tells us nothing about the code -- do not mistake that for a
    # clean baseline.
    if proc.returncode not in (0, 1):
        sys.stderr.write(output)
        sys.exit(f"mypy failed to run (exit {proc.returncode}); see output above")
    return output


def parse(output: str) -> Counter[tuple[str, str]]:
    """Reduce mypy output to a {(file, error-code): count} tally."""
    tally: Counter[tuple[str, str]] = Counter()
    for line in output.splitlines():
        match = ERROR_RE.match(line.strip())
        if match:
            # Windows emits backslashes; the baseline is checked in, so it has
            # to read the same on every platform.
            path = match.group("file").replace("\\", "/")
            tally[(path, match.group("code"))] += 1
    return tally


def load_baseline() -> Counter[tuple[str, str]]:
    tally: Counter[tuple[str, str]] = Counter()
    if not BASELINE_PATH.exists():
        return tally
    for raw in BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        count, path, code = line.split("\t")
        tally[(path, code)] = int(count)
    return tally


def write_baseline(tally: Counter[tuple[str, str]]) -> None:
    lines = [
        f"{count}\t{path}\t{code}" for (path, code), count in sorted(tally.items())
    ]
    BASELINE_PATH.parent.mkdir(parents=True, exist_ok=True)
    BASELINE_PATH.write_text(HEADER + "\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the baseline from the current mypy output",
    )
    args = parser.parse_args()

    current = parse(run_mypy())

    if args.update:
        write_baseline(current)
        total = sum(current.values())
        print(f"Wrote {BASELINE_PATH.relative_to(REPO_ROOT)}: {total} errors")
        return 0

    baseline = load_baseline()

    regressions = sorted(
        (path, code, count - baseline.get((path, code), 0))
        for (path, code), count in current.items()
        if count > baseline.get((path, code), 0)
    )
    fixed = sorted(
        (path, code, baseline[(path, code)] - current.get((path, code), 0))
        for (path, code) in baseline
        if current.get((path, code), 0) < baseline[(path, code)]
    )

    if fixed:
        print(
            f"{len(fixed)} baseline entr{'y' if len(fixed) == 1 else 'ies'} improved:"
        )
        for path, code, delta in fixed:
            print(f"  -{delta}  {path}  [{code}]")
        print("Run `python tools/check_mypy_baseline.py --update` to resync.\n")

    if regressions:
        new_errors = sum(delta for _, _, delta in regressions)
        print(f"FAIL: {new_errors} new mypy error(s) beyond the baseline:\n")
        for path, code, delta in regressions:
            was = baseline.get((path, code), 0)
            now = current[(path, code)]
            detail = f"was {was}, now {now}" if was else "new"
            print(f"  +{delta}  {path}  [{code}]  ({detail})")
        print(
            "\nFix them, or -- if they are genuinely acceptable -- run"
            "\n  python tools/check_mypy_baseline.py --update"
            "\nand explain the new entries in the commit message."
        )
        return 1

    print(f"OK: {sum(current.values())} mypy error(s), all within the baseline.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
